### PR TITLE
Add 3.14-rc variants

### PR DESCRIPTION
**Pull request by sspans-sbp**
Python 3.14 is still in development. This release, 3.14.0a1 is the first of seven planned alpha releases.

https://www.python.org/downloads/release/python-3140a1/

### CODE REVIEW

**Comment by sspans-sbp** [comment]
I'll update the PR with the correct GPG key in a bit...

**Comment by jnoordsij** [comment]
https://peps.python.org/pep-0761/ seems to confirm that Python is indeed moving from PGP to Sigstore. For >= 3.11 this seems to be in place, so a full migration would not be possible yet; so probably this would require distinguishing versions and implementing two different ways to verify artefacts.

**Comment by yosifkit** [comment]
https://github.com/docker-library/python/issues/977#issuecomment-2403109432

So, I think we'll have to just remove the gpg verification for `3.14` and above and solely rely on the sha256 check (https://github.com/docker-library/python/pull/978) until there is a secure/verifiable way (like an `apt` package in Debian) to get a sigstore client to check the sigstore signature.

**Comment by tianon** [comment]
Updated with an appropriate conditional to remove the PGP logic for 3.14+ :eyes:

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
