### PR TITLE
Prueba pull request

### PR DESCRIPTION
**Pull request by ghost**
Prueba de pull request con implementaciones ficticias.

### CODE REVIEW

**Comment by tianon** [comment]
In the future, please perform tests like this against your own personal repositories (instead of spamming others).

**Comment by cgrane1** [comment]
I'm terribly sorry about it. I'm taking a course about Git and Github and the teacher told me to use your repository for a small test of fork and pull request. He told me to close the pull request fast to avoid problems, but I'm afraid it wasn't enough. I will tell the teacher not to use this repository anymore. I'm sorry.

**Comment by tianon** [comment]
That explains the number of times we've had this same type of spammy content. :sob:

I would suggest your teacher should create their own repository and have students send their PRs there instead (so that your teacher is the only person receiving the PR spam).

**Comment by cgrane1** [comment]
I wrote to the teacher again suggesting him to create his own repository. It's not a difficult task, I don't know why he didn't do that instead of spamming other people's repositories. I hope he will do it before another student takes the course. I apologize again for all the trouble.

**Comment by tianon** [comment]
Thank you so much for trying to help us communicate with your teacher -- it's really appreciated!

**Comment by cgrane1** [comment]
You're welcome, but It was the least I could do.

**Comment by cgrane1** [comment]
Hi! Since I already finished the course, and I guess that I won't need the account anymore (I doubt I'll use this tools in the future), I'll delete it soon. I hope the teacher changes the course and nobody uses your repository for tests anymore.

**Pull request closed without merging**
