### PR TITLE
Add tag for Alpine 3.10

### LINKED ISSUE #398: Is it planned to release a alpine 3.10 based docker image for python 3.7?
Looking at Dockerfile all I can see is alpine 3.9 and alpine 3.10 is available :)

Thanks again

### PR DESCRIPTION
**Pull request by J0WI**
Closes #398

### CODE REVIEW

**Comment by ulgens** [comment]
The issue is closed and PR is merged, but there is no PR about the change to official-images repo yet. How much should we wait? Is it an automated process or someone's responsibility?

Edit: I saw this just after i wrote the comment.

> added a commit to docker-library-bot/official-images that referenced this pull request 2 days ago

It seems that PR was created in no time, but i'm not sure it targets the right repo.

**Comment by J0WI** [comment]
A PR has not yet been created:
https://github.com/docker-library/official-images/compare/master...docker-library-bot:python

**Comment by ulgens** [comment]
@J0WI Thanks. So, how does the process work? Is there a trigger for that or someone creates it manually? Also, why do we have https://github.com/docker-library-bot/official-images/commit/bc698b600e925f5116baa63f18579e05e2ef3407 this PR and what does it do?

**Comment by J0WI** [comment]
I don't know why @docker-library-bot haven't submitted the PR so far. They may want to merge #402 first to avoid rebuilding everything twice.

**Comment by ulgens** [comment]
@J0WI Is it something we can debug?

**Comment by tao12345666333** [comment]
Please see https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what to understand the process.

**Comment by ulgens** [comment]
@tao12345666333 That's the issue. These steps doesn't work right now. We are stuck at step 2.

**Comment by tao12345666333** [comment]
@ulgens  we can just open a PR for this. https://github.com/docker-library/official-images/pull/6166

**Comment by yosifkit** [comment]
The bot only creates us some [branches](https://github.com/docker-library-bot/official-images/branches) and then @tianon or I will go press the pull request button while double checking that the changes make sense (or if there is another PR that could be included soon to reduce image churn for users). Really anyone could press the "new pull request" button there, since they are all based on changes already committed to the individual repos.

**Comment by ulgens** [comment]
@yosifkit Thanks for the details. I understand the reasoning but "putting updates in Docker Hub" is already a painfuly slow process, and this review - PR process added 3 days to that. Is there any way to make it faster - automated?

**Pull request merged**
