### PR TITLE
Configure Python with --enable-unicode=ucs4

### PR DESCRIPTION
**Pull request by Starefossen**
Ref. #21 I went ahead and added the `--enable-unicode=ucs4` configuration flag.

Maybe this could be solved via a `PYTHON_CONFIGURE_OPTS` environment variable?

### CODE REVIEW

**Comment by tianon** [comment]
This seems reasonable to me. :+1:

@paultag since you have really strong opinions on Python and UTF8, care to weigh in?

https://docs.python.org/2/c-api/unicode.html
> This type represents the storage type which is used by Python internally as basis for holding Unicode ordinals. Python’s default builds use a 16-bit type for Py_UNICODE and store Unicode values internally as UCS2. It is also possible to build a UCS4 version of Python (most recent Linux distributions come with UCS4 builds of Python). These builds then use a 32-bit type for Py_UNICODE and store Unicode data internally as UCS4. On platforms where wchar_t is available and compatible with the chosen Python Unicode build variant, Py_UNICODE is a typedef alias for wchar_t to enhance native platform compatibility. On all other platforms, Py_UNICODE is a typedef alias for either unsigned short (UCS2) or unsigned long (UCS4).

https://docs.python.org/3/c-api/unicode.html also has this interesting tidbit: (but not much else one way or another)
> When dealing with single Unicode characters, use Py_UCS4.

**Comment by paultag** [comment]
Euch, sorry, was going to reply, yeah this seems entirely reasonable to me!

:+1:

**Comment by tianon** [comment]
LGTM

**Comment by tianon** [comment]
(thanks @paultag :heart:)

**Comment by yosifkit** [comment]
LGTM

**Comment by Starefossen** [comment]
Does anyone know when the image on Docker Hub will be updated?

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/pull/528 for progress
on that.

**Pull request merged**
