### PR TITLE
Add Alpine 3.7 variants for 2.7 & 3.6, move 3.7 to Alpine 3.7

### LINKED ISSUE #245: Alpine 3.7
[Alpine 3.7 was released](https://alpinelinux.org/posts/Alpine-3.7.0-released.html), so could a base that uses that be added?

### PR DESCRIPTION
**Pull request by JayH5**
Fixes #245

### CODE REVIEW

**Comment by tianon** [comment]
(Planning to merge once Travis is happy)

**Comment by daveisfera** [comment]
Is there a [PR for the official images to build](https://github.com/docker-library/official-images/pulls)?

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/3815

**Comment by askoretskiy** [comment]
Thanks @tianon !

**Pull request merged**
