### PR TITLE
[RFC] Add 3.5/alpine variant

### PR DESCRIPTION
**Pull request by ncopa**
This is a continuation of #71 which was deleted by mistake.

I have made incremental changes for displaying the progress. I can merge the patches into a single before we merge it into docker-library if wanted.

### CODE REVIEW

**Comment by ncopa** [comment]
Seems that the tests are failing due to missing bash and readline. Those were intentionally excluded so I guess we need to fix the test suite.

**Comment by tianon** [comment]
Figured I'd just PR my comments so they're easier to discuss and/or incorporate: https://github.com/ncopa/python/pull/1 :smile:

**Comment by tianon** [comment]
I've restarted the CI job now that the test is fixed -- this LGTM (going to wait for CI to come back green though)

**Comment by tianon** [comment]
Oh right, readline.  We'll need to do something with that test, but I don't think this is worth holding up on account of that. :+1:

**Comment by tianon** [comment]
Hmm, it _does_ only add ~2.75 MB to install.  Still worth considering just adding it, since it's a core Python module -- does installing it after the fact enable the core module, or does it have to be built in during Python source compilation time?  If it's hard or impossible to add after the fact, then I think we need to just include it unilaterally, but if we can add it afterwards without too much trouble, then we're fine and need to fix the test.

**Comment by tianon** [comment]
```console
$ docker run -it --rm python:alpine sh
/ # apk add --no-cache readline
fetch http://dl-4.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-4.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/1) Installing readline (6.3.008-r4)
Executing busybox-1.24.1-r7.trigger
OK: 13 MiB in 18 packages
/ # python
Python 3.5.1 (default, Dec 31 2015, 22:51:08) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import readline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'readline'
>>> 
```
:disappointed: :cry:

BUT!  The silver lining is that we already have the deps of `readline` installed, so it only takes up an extra ~638.9 kB. :+1: :metal:

**Pull request merged**
