### PR TITLE
Add alpine 3.6 variant

### PR DESCRIPTION
**Pull request by skwashd**

### CODE REVIEW

**Comment by tianon** [comment]
> See https://github.com/docker-library/python/pull/166, https://github.com/docker-library/python/pull/168, and https://github.com/docker-library/golang/pull/131#issuecomment-270677556.

**Comment by skwashd** [comment]
Changes made as suggested by @tianon on [issue #173](https://github.com/docker-library/python/issues/173#issuecomment-305331880).

The [3.6-alpine3.6 build failed](https://travis-ci.org/docker-library/python/jobs/2394373340) while trying to verify the signature. This appears to be a transient issue. When I tried locally the first time it failed, 5 minutes later it worked. Last week [it built fine using alpine:3.6](https://travis-ci.org/docker-library/python/jobs/237793484) for all versions. The [2.7-alpine3.6 build](https://travis-ci.org/docker-library/python/jobs/239437357) passed. Can `$someone` please rerun the [239.3 build](https://travis-ci.org/docker-library/python/jobs/239437334)?

**Comment by tianon** [comment]
Newer `gpg` is less forgiving about deleting the directory (socket files that we have a race condition with some agent cleaning up after itself while we delete) -- merging anyhow (will clean that up after). :+1:

**Comment by JayH5** [comment]
Should this not be using LibreSSL instead of OpenSSL?

**Comment by skwashd** [comment]
@JayH5 good point. I've submitted PR #203 to make that change. I'd appreciate any other feedback you have.

**Pull request merged**
