### PR TITLE
Adjust installation order and purge "libpythonXX.a" files

### LINKED ISSUE #503: Removing Win386 executables from images
Debian based images contain windows executables inside . Those files are never used and not necessary at all on debian based images:

```
$ docker run -it --entrypoint /usr/bin/find python:3.8-slim / -iname '*.exe' -exec du -ch {} +
100K	/usr/local/lib/python3.8/site-packages/pip/_vendor/distlib/w64.exe
104K	/usr/local/lib/python3.8/site-packages/pip/_vendor/distlib/t64.exe
88K	/usr/local/lib/python3.8/site-packages/pip/_vendor/distlib/w32.exe
96K	/usr/local/lib/python3.8/site-packages/pip/_vendor/distlib/t32.exe
64K	/usr/local/lib/python3.8/site-packages/setuptools/cli-32.exe
76K	/usr/local/lib/python3.8/site-packages/setuptools/cli-64.exe
64K	/usr/local/lib/python3.8/site-packages/setuptools/gui-32.exe
64K	/usr/local/lib/python3.8/site-packages/setuptools/cli.exe
64K	/usr/local/lib/python3.8/site-packages/setuptools/gui.exe
76K	/usr/local/lib/python3.8/site-packages/setuptools/gui-64.exe
192K	/usr/local/lib/python3.8/distutils/command/wininst-9.0.exe
220K	/usr/local/lib/python3.8/distutils/command/wininst-9.0-amd64.exe
188K	/usr/local/lib/python3.8/distutils/command/wininst-10.0.exe
64K	/usr/local/lib/python3.8/distutils/command/wininst-7.1.exe
220K	/usr/local/lib/python3.8/distutils/command/wininst-10.0-amd64.exe
60K	/usr/local/lib/python3.8/distutils/command/wininst-6.0.exe
448K	/usr/local/lib/python3.8/distutils/command/wininst-14.0.exe
60K	/usr/local/lib/python3.8/distutils/command/wininst-8.0.exe
576K	/usr/local/lib/python3.8/distutils/command/wininst-14.0-amd64.exe
2.8M	total
```

Affected images are: 
 * python:3.8-buster
 * python:3.8-buster-slim
 * python:3.7-buster
 * python:3.7-buster-slim
 * python:3.7-stretch
 * python:3.7-slim-stretch
 * python:3.7-alpine3.12
 * python:3.7-alpine3.11
 * python:3.6-buster
 * python:3.6-buster-slim
 * python:3.6-stretch
 * python:3.6-slim-stretch
 * python:3.6-alpine3.12
 * python:3.6-alpine3.11
 * python:rc-buster (missing distutils/command/wininst-*.exe)

I haven't tested the 3.5.* line. Probably is the same.

### LINKED ISSUE #507: Utility of the static linked library in the image if --enable-shared is active
Hello,

I was wondering why the static library libpythonXX.a (example in the alpine: /usr/local/lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8.a) was kept in the docker image for all the image variance, while the --enable-shared flag is active for the compilation process. That file is around 50% of the image size on the alpine.

I am assuming this is intended for the usage of some use case where you might need to link some code directly to it, but the documentation of the image only make reference to using the image as base, including our own script and just run it with python (which seems to be dynamically linked to the .so files).

I am mostly curious to know if this is intended or if this is an oversight from a few year ago when the --enable-shared flag was added.

### PR DESCRIPTION
**Pull request by tianon**
Closes #507
Closes #503
Closes #504

### CODE REVIEW

**Comment by tianon** [comment]
(Cognitively, I think it makes sense to finish everything we need to do with the source code, then purge all traces of the source code, then purge files we didn't want to have installed, *then* detect necessary dependencies, hence my reordering.)

**Comment by tianon** [comment]
A couple size comparisons (before / after):

- `python:3.8-alpine3.12`: 80.3MB / 42.7MB
  - https://github.com/docker-library/python/runs/921941015?check_suite_focus=true#step:8:12
  - https://github.com/docker-library/python/pull/508/checks?check_run_id=934002412#step:8:14
- `python:3.8-slim-buster`: 165MB / 168MB
  - https://github.com/docker-library/python/runs/921940999?check_suite_focus=true#step:8:15
  - https://github.com/docker-library/python/pull/508/checks?check_run_id=934002405#step:8:15

(That slight increase on `3.8-slim-buster` is curious :eyes: )

**Comment by tianon** [comment]
I built before/after locally to help minimize differences in the packages installed, etc to try and narrow down why `python:3.8-slim-buster` got slightly bigger:

- Before: ~165MB
- After: ~169MB

(In other words, building locally didn't actually help narrow down anything....)

This will have to be a project for next week. :disappointed:

**Comment by Lebvanih** [comment]
Hello,

The size increase that you see on the debian buster slim seems to come from the ordering.
If I take the new docker file and stop it after the build of python (so before the part for PIP) and then check the amount of package installed on the system:
root@b96d018c9659:/usr# dpkg --list | wc -l
123

If I check the same on the old image:
root@e1e2a2280dd3:/usr# dpkg --list | wc -l
98

I am not really and expert with ldconfig and what it does and how this affect the whole build, but it seems that if ldconfig is placed at the end, this part clean less package during the apt-get purge resulting in more space used in /usr/lib and /usr/share directory:
After:
```
root@b96d018c9659:/usr# du -xhs *
14M	bin
4.0K	games
9.8M	include
55M	lib
26M	local
2.0M	sbin
38M	share
4.0K	src
```
Before:
```root@e1e2a2280dd3:/usr# du -xhs *
14M	bin
4.0K	games
4.0K	include
33M	lib
85M	local
2.0M	sbin
6.9M	share
4.0K	src
```
The line of the dockerfile i'm mentionning:
```
find /usr/local -type f -executable -not \( -name '*tkinter*' \) -exec ldd '{}' ';' \
		| awk '/=>/ { print $(NF-1) }' \
		| sort -u \
		| xargs -r dpkg-query --search \
		| cut -d: -f1 \
		| sort -u \
		| xargs -r apt-mark manual \
	&& apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
```
I tried to move the ldconfig line above the two mentioned above and I got back to 98 packages visible from dpkg --list.
If I recheck on my image (still without pip for the comparison):
```
root@2e927fb79cf3:/usr# du -xhs *
14M	bin
4.0K	games
4.0K	include
33M	lib
26M	local
2.0M	sbin
6.9M	share
4.0K	src
```
Adding the part with pip I get this size:
```
REPOSITORY                                               TAG                 IMAGE ID            CREATED             SIZE
cleaned3                                                 latest              449a3f524048        5 seconds ago       113MB
``` 
The only difference with your dockerfile is the place of the ldconfig.
How it looks on mine:
```	
       && apt-mark auto '.*' > /dev/null \
	&& apt-mark manual $savedAptMark \
	\
	&& ldconfig \
	&& find /usr/local -type f -executable -not \( -name '*tkinter*' \) -exec ldd '{}' ';' \
		| awk '/=>/ { print $(NF-1) }' \
		| sort -u \
		| xargs -r dpkg-query --search \
		| cut -d: -f1 \
		| sort -u \
		| xargs -r apt-mark manual \
	&& apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
	&& rm -rf /var/lib/apt/lists/* \
	\
	&& python3 --version
```
Hoping this helps, as I said, I am not an expert, so I am not sure why this is affecting, but as you moved it in this commit, I tried to see if that could be the issue of the size change.

**Comment by tianon** [comment]
Yeah, great catch!  I realized right after I left for the day on Friday that I can't `ldconfig` before I `ldd`, and that was probably exactly the reason for the discrepancy. :facepalm: 

After fixing that:

- `python:3.8-slim-buster` before: ~172MB (freshly built)
- `python:3.8-slim-buster` after: ~120MB

Much better :innocent:

**Comment by tianon** [comment]
This helped me notice https://github.com/docker-library/python/pull/439#issuecomment-668195894 (we missed `slim-buster` variants entirely for `3.9-rc`, so we should add those back after we finish this).

**Pull request merged**
