### PR TITLE
Upgrade alpine to v3.5

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by tianon** [comment]
I'm +1 on the change, but only after the Alpine image maintainers update `latest` to point to `3.5` (see https://github.com/docker-library/official-images/pull/2489#discussion_r93885746).

**Comment by askoretskiy** [comment]
+1 from me. Proposed almost the same PR )

**Comment by PeterDaveHello** [comment]
@tianon now the `alpine:latest` is same as `alpine:3.5` :)

**Comment by askoretskiy** [comment]
Congrats ))

**Comment by askoretskiy** [comment]
@tianon Would you merge it? (since alpine 3.5 is "latest")

**Comment by tianon** [comment]
Revert incoming in #168 -- see https://github.com/docker-library/golang/pull/131#issuecomment-270677556 for more details.

**Pull request merged**
