### PR TITLE
Disable pip cache

### PR DESCRIPTION
**Pull request by orgads**
It is useless in docker envs, and just takes space.

### CODE REVIEW

**Review by ad-m-ss — COMMENTED** [review]
LGTM 👍 

FTR: Downstream image may leverage pip cache by:

```
FROM python:3.10.7-bullseye AS build-pip
ENV PIP_CACHE_DIR=/var/cache/buildkit/pip
RUN mkdir -p $PIP_CACHE_DIR
RUN --mount=type=cache,target=/var/cache/buildkit/pip \
    pip install -U pip wheel
```

**Comment by orgads** [comment]
> FTR: Downstream image may leverage pip cache by:
> 
> ```
> FROM python:3.10.7-bullseye AS build-pip
> ENV PIP_CACHE_DIR=/var/cache/buildkit/pip
> RUN mkdir -p $PIP_CACHE_DIR
> RUN --mount=type=cache,target=/var/cache/buildkit/pip \
>     pip install -U pip wheel
> ```

Not exactly. You'll also need:
```
ENV PIP_NO_CACHE_DIR=
```

**Comment by tianon** [comment]
I definitely sympathize with the motivation here (and want this myself for my own `FROM python` images!), but I do worry about the impact of setting explicit defaults for these, _especially_ when disabling our tweaks to the defaults is (as you've demonstrated) not entirely straightforward/obvious.  Even if this is what most users actually want, it _is_ a surprising moment when they discover that the defaults they thought applied (and that the `pip` documentation describes applying!) actually do _not_ seem to apply in practice. :sweat_smile:

**Comment by orgads** [comment]
I understand your concern. I'll try to check what other popular image do wrt caching.

**Comment by orgads** [comment]
Ok, you're probably right. I also see that it is a common practice to use a mount for the cache, which will be broken if this change is accepted.

So maybe we should just recommend setting this variable in the README instead?

**Comment by orgads** [comment]
Actually I see that the [documentation](https://hub.docker.com/_/python/) of the image already uses `--no-cache-dir` in the example, so I guess no further action is needed:

```
RUN pip install --no-cache-dir -r requirements.txt
```
(notice that this affects only the packages that are installed during the build, and has no effect when running pip in the container, but this is less important).

Also this doesn't cover packages that require build. See https://github.com/pypa/pip/issues/12031

**Pull request closed without merging**
