### PR TITLE
Add jammy and kinetic (ubuntu 22.04 and 22.10)

### PR DESCRIPTION
**Pull request by tuler**
My end goal is to build images for `linux/riscv64` architecture.
The problem is that the base used here is [debian](https://hub.docker.com/_/debian) and that doesn't have an official `riscv64` build yet. On the other hand [ubuntu](https://hub.docker.com/_/ubuntu) images already have `riscv64` official builds.

Another separate problem is the integration in the build system, which I believe is based on a Jenkins system, to build riscv64 images. I successfully built riscv64 images in my local arm64 Apple M1 using docker buildx riscv64 support through qemu.

This PR is only about adding ubuntu based images though, which will help to achieve the goal of having riscv64 images.

### CODE REVIEW

**Comment by tianon** [comment]
See https://github.com/docker-library/python/issues/708

**Review by mudanzasIPROM — COMMENTED** [review]
Hola

**Review by mudanzasIPROM — COMMENTED** [review]
Hjjjj

**Comment by yosifkit** [comment]
Just an FYI, Ubuntu has dropped `riscv64` images, for now: https://github.com/docker-library/official-images/pull/13950#issuecomment-1412111952.

**Comment by tuler** [comment]
Another alternative for adding `linux/riscv64` support for the official python image is to add the `unstable` and `slim-unstable` debian variants.

Those [debian variants](https://hub.docker.com/layers/library/debian/unstable/images/sha256-2482c72e0ad01ae8d942689c725d72429fb579fd37ecf3c61282eb98c2479fb5?context=explore) at docker hub has builds for `linux/riscv64`, as well as [buildpack-deps:unstable](https://hub.docker.com/layers/library/buildpack-deps/unstable/images/sha256-3a887968fe43226ca614e3bdfba591197b3593e08bde65a9a38a179bf5715812?context=explore).

Would you be interested in having a `python:unstable` as well?

**Comment by tianon** [comment]
Unfortunately, as the name implies, Debian Unstable is a fairly unstable base to build on top of, and is frequently broken (by design), so we don't have very many official images based on it (and would prefer not to maintain any ourselves).

**Comment by tuler** [comment]
@cjdcordeiro we are not seeing `linux/riscv64` builds for [buildpack-deps](https://hub.docker.com/layers/library/buildpack-deps/jammy/images/sha256-e902a5ede3335b40edf720db97f0f318f2f014bf34395671c61dd7c554c38967?context=explore) anymore/yet. Will they be added?

**Comment by cjdcordeiro** [comment]
> @cjdcordeiro we are not seeing `linux/riscv64` builds for [buildpack-deps:jammy](https://hub.docker.com/layers/library/buildpack-deps/jammy/images/sha256-e902a5ede3335b40edf720db97f0f318f2f014bf34395671c61dd7c554c38967?context=explore) anymore/yet. Will they be added?

@tuler yes they will. It requires a few changes in our build systems in order to make both i386 and riscv64 coexist across the spectrum of currently supported releases, but we **do intend** do start publishing for riscv64 again. It is currently being worked on but I don't yet have an ETA.

**Comment by tuler** [comment]
> > @cjdcordeiro we are not seeing `linux/riscv64` builds for [buildpack-deps:jammy](https://hub.docker.com/layers/library/buildpack-deps/jammy/images/sha256-e902a5ede3335b40edf720db97f0f318f2f014bf34395671c61dd7c554c38967?context=explore) anymore/yet. Will they be added?
> 
> @tuler yes they will. It requires a few changes in our build systems

@cjdcordeiro any update on this?

**Comment by tianon** [comment]
Sorry, we unfortunately have no plans to support Ubuntu based images here (our matrix is already pretty large supporting all actively supported release lines of Python upstream multiplied by 2x Debian + 2x Alpine + 2x Windows _and_ their respective sets of supported CPU architectures and Python is relatively heavy to build).

**Comment by cjdcordeiro** [comment]
FYI (and especially for @tuler) the riscv64 support for Ubuntu container images is being worked on atm. It is already in QA and should reach the official images soon.

**Pull request closed without merging**
