### PR TITLE
Use "dpkg-divert" instead of "purge" to avoid Debian's Python

### LINKED ISSUE #129: pkg-config, libfreetype6-dev missing
It looks like as of yesterday `pkg-config` and `libfreetype6-dev` (and presumably other packages) are no longer in `python:2.7` (and presumably other tags). Was this deliberate and should I just start installing these myself in my images?

### PR DESCRIPTION
**Pull request by tianon**
Fixes #129

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM

**Comment by os** [comment]
This is going to cause issues for people who are using Supervisor as this is going to remove pre-installed version. You can't run Supervisor with Python 3 and this is removing the old one.

```
bash: /usr/bin/supervisord: /usr/bin/python: bad interpreter: No such file or directory
```

**Comment by glynjackson** [comment]
What is the reason behind this commit? a whole set of issues arise as @os has commented.

**Comment by mozbhearsum** [comment]
There's some background in https://github.com/docker-library/python/issues/132#issuecomment-235691116. tl;dr - running purge removes some pcre dev libraries, which cause some things (notably uwsgi) to compile without necessary features.

**Pull request merged**
